service: authorization-service
frameworkVersion: '3'
useDotenv: true
package:
  individually: true
plugins:
  - serverless-esbuild
  - serverless-offline

provider:
  name: aws
  runtime: nodejs14.x
  stage: dev
  region: eu-central-1
  environment:
    NAME: ${env:NAME}
    PASSWORD: ${env:PASSWORD}

functions:
  basicAuthorizer:
    handler: handler.basicAuthorizer
    events:
      - http:
          method: get
          path: import
          cors:
            origin: ${self:custom.CLOUDFRONT}
          integration: lambda
          request:
            parameters:
              querystrings:
                fileName: true

custom:
  esbuild:
    bundle: true
    minify: false
    sourcemap: true
    exclude:
      - aws-sdk
    target: node14
    platform: node
    concurrency: 10
  CLOUDFRONT: https://d24quk142c4yyb.cloudfront.net
  dotenv:
    path: ../../../rds/.env
