service: product-service
frameworkVersion: "3"
package:
  individually: true
# Add the serverless-webpack plugin
plugins:
  - serverless-webpack
  - serverless-openapi-documentation

provider:
  name: aws
  runtime: nodejs14.x
  stage: dev
  region: eu-central-1

functions:
  getProductsList:
    handler: handler.getProductsList
    events:
      - http:
          method: get
          path: products
          cors: true
          integration: lambda
          documentation: ${file(serverless.doc.yml):documentation.endpoints.getProductsList}
  getProductsById:
    handler: handler.getProductsById
    events:
      - http:
          method: get
          path: products/{productId}
          cors: true
          integration: lambda
          documentation: ${file(serverless.doc.yml):documentation.endpoints.getProductsById}

custom:
  webpack:
    webpackConfig: "webpack.config.js"
    packager: "npm"
    includeModules: true
  documentation: ${file(serverless.doc.yml):documentation}
