service: product-service
frameworkVersion: '3'
package:
  individually: true
# Add the serverless-webpack plugin
plugins:
  - serverless-webpack
  - serverless-offline
  - serverless-dotenv-plugin
provider:
  name: aws
  runtime: nodejs14.x
  stage: dev
  region: eu-central-1

functions:
  getProductsList:
    handler: handler.getProductsList
    events:
      - http:
          method: get
          path: products
          cors:
            origin: ${self:custom.CLOUDFRONT}
          integration: lambda
  getProductsById:
    handler: handler.getProductsById
    events:
      - http:
          method: get
          path: products/{productId}
          cors:
            origin: ${self:custom.CLOUDFRONT}
          integration: lambda
  postProduct:
    handler: handler.postProduct
    events:
      - http:
          method: post
          path: products
          cors:
            origin: ${self:custom.CLOUDFRONT}
          integration: lambda
custom:
  webpack:
    webpackConfig: 'webpack.config.js'
    packager: 'npm'
    includeModules: true
  CLOUDFRONT: d24quk142c4yyb.cloudfront.net
  dotenv:
    path: ../../../rds/.env
